### ISSUE TITLE
Add cooldown with callback

### ISSUE THREAD

**Issue by kurosio** [kurosio/Teeworlds-MRPG-0.6#11]
For example, when using some actions in quests. there will be a progress bar with numbers cooldown.

I envision it at the moment.

```cpp
{
     // some code inside {}
     CCooldown* pCol = CreateCooldown(/*timer*/, /*some callback*/); // destructor inside object on handle time
}
```

**Comment by Anime-pdf** [comment]
resolved in https://github.com/kurosio/Teeworlds-MRPG-0.6/commit/f1219840
